### ISSUE TITLE
Generisk RAR-støtte i Maskinporten

### ISSUE THREAD

**Issue by joergenb** [felleslosninger/product_maskinporten#2]
RAR-spec'en er p.t. ikkje støtta i Maskinporten.

Oppgåva er å legge til RAR-støtte på ein generisk måte, truleg etter same modell som i Ansattporten, der me trigger på at `authorization_details` er tilstades i grantet, og so har ein router-funksjonalitet som let eigne plugins/mikrotenester kunne handtere kvar RAR-type (`type`).

Det er ein heil del aspekt som må vurderast, og truleg bør me gå for enklaste realisering i første runde. 

- [x] *Skal det vere lov å bruke RAR og scopes samstundes? *   I starten: ja.  Maskinporten utsteder ikkje tokens utan scope idag, og dette ynskjer me ikkje endra ved innføring av RAR.   På sikt kan det verte aktuelt med frikopling, slik også spec'en anbefalar.
- [x] *Dersom ja, trengs det validering av at scope og rar-type "heng saman" ?*   Nei.  API-tilbydar må bruke scopes som tilgangstyring for RAR (sjå under), og sjølv utføre validering av forventa scope-rar_type-kombinasjon i APIet.
- [ ] *Kva skal me returnere om ingen rar-element er tilfredstilt ? *   Slik me tolkar spec, er det berre syntaktisk valideringsfeil ihht datamodellen som skal føre til 400 BAD REQUEST.  I tilfelle der ingen førespurte rar-element kan  utleverast av Autorisasjon/annan datakjelde, so vil tokenet mangle `authorization_details`.  API-tilbydar må validere på dette, og returnere ein fornuftig feilmelding til klient.
- [x] *Skal me støtte grants som ber om fleire rar-element av same type ?* I prinsippet kan `authorization_details` vere ein array av ulike `type`,  så generisk må me legge opp til det.   Men ikkje sikker at definisjon av den aktuelle `type` er slik at det gjev meining å ha fleire element i token.  Kan utløyse behov for å lage regelsett for rar, ikkje del av scope no.  Kan også løysast ved at rar-typen har array som datatype for aktuelle claims
- [ ] *Skal me støtte grants som ber om fleire rar-element av ulik type ? * Prinsippielt er svaret "ja".  Men det kan godt tenkast at to typar er gjensidig ekskluderande, eller det vil vere andre vilkår for at begge elementa skal gjelde.  Kan som over utløyse behov for regelsett, noko me ikkje ynskjer laga no.
- [ ] *Beslutte kvar validering av datamodell skal ligge*   Dette er enklare enn i ID-porten, for det er uansett ikkje nokon sluttbrukar som kan bli påverka ved f.eks ein "halvvegs innlogging".  Maskinporten kan i prinsippet outsource all validering til Datakjelde (Autorisasjon) for dei enkle datamodellane me kjenner no.
- [ ] Beslutte akseptable timeout-verdiar mot eksterne kjelder
- [x] *Skal det vere tilgangstyring av rar-typar (som for scopes), eller skal alle kundar kunne be om alle rar-typar ?* Optimalt sett bør RAR-tilgangstyrast på tilsvarande måte som scopes, men kan verte meir komplisert avhengig av kva datamodell som ligg til grunn for typen.   I starten lagar me ingen tilgangstyring, API-tilbydar må bruke scopes som tilgangstyring for RAR.
- [x] *Treng vi å innføre full token-levetid-begrensningar per RAR-type, slik som me har for scope ?  Viss "ja", korleis skal RAR-levetid og scope-levetid sameksistere?*   Ingen eigen levetidsbegrensningar for rar-type, API-tilbydar må bruke eksisterande scope-mekanisme

```[tasklist]
### Tasks
```
